### ISSUE TITLE
Urlgen dropping the collection folder from the url

### ISSUE THREAD

**Issue by claybarrett** [jbest/powersorter#1] opened 2021-07-07 15:54 UTC
Testing I found that the link url_gen makes in v3 is
[https://web.corral.tacc.utexas.edu/torch/OKLA0101000/OKLA101219_med.jpg](url)
instead of 
[https://web.corral.tacc.utexas.edu/torch/OKLA/OKLA0101000/OKLA101219_med.jpg](url)
This happened to all three links, not just the Med.

**Comment by jbest** [comment] 2021-07-07 16:48
Clay, can you attach the config file you used when encountering this problem?

**Comment by claybarrett** [comment] 2021-07-07 16:52
[OKLA.txt](https://github.com/jbest/powersorter/files/6778878/OKLA.txt)

It won't let me attach JSON, so here's it renamed as TXT. The only thing that's changed is the input_path target.

**Comment by jbest** [comment] 2021-07-09 22:12
The problem is because in v2 configs we didn't have a web_base for each collection so the general web base for ALL collections was hard coded into the script and the way I calculated the web URL is no longer correct in v3 configs where we specify a web_base unique to each collection.

**Comment by jbest** [comment] 2021-07-09 22:47
This has been fixed and merged into main, please test on TACC in dev/powersorter/

**Closed as completed by jbest** 2021-07-09 22:47 UTC
